### ISSUE TITLE
Support för engelska

### ISSUE THREAD

**Issue by smart-ctrl** [krissen/pollenprognos-card#4]
Önskar översättning av veckodagar och texter till engelska, d,v,s, support för engelska.
Eller ännu bättre om det ges möjlighet att göra översättningen själv.

![image](https://github.com/krissen/pollenprognos-card/assets/85099988/a872220b-6395-40c2-952f-f044b2c38083)

**Comment by Dav-rnd** [comment]
+1 on this.
I would really like to be able to use english, or other languages, for this card. 

More precisely, we need the ability to set custom display text in the UI for:

- today/tomorrow, days of the week
- allergens names

A possible good way to do this would be to allow a custom text value for swedish words appearing in the UI, that the user could customize in the configuration for the card.

What do you think? Dos that sound feasible?

**Comment by krissen** [comment]
@smart-ctrl, really sorry about not responding. Totally missed this.

@Dav-rnd, feasible — for sure!

I apologize for seeming lazy, but I'm simply swamped at work currently. If you're able to, please propose a solution and make a PR! 🙏 Meanwhile, this is filed under "todo when there's time".

**Comment by krissen** [comment]
@smart-ctrl @Dav-rnd Check out pre-release [v1.1.0b](https://github.com/krissen/pollenprognos-card/tree/v1.1.0b)! Support for customising all phrases has been added. See [README](https://github.com/krissen/pollenprognos-card/blob/custom-phrases/README.md) in the branch custom-phrases for instructions (all the way down on the page).

By copying the example, you'd get a full English translation like so:

<img width="377" alt="Image" src="https://github.com/user-attachments/assets/c81c6cea-474e-421f-b23e-047d2e5e1e82" />

Adjust phrases to your liking.

Please confirm if it works for you! If it does, I'll make a proper release of it.

**Note** that this is based on v1.0.6, meaning that your sensor integration needs to have been upgraded to 1.1.0! See [release notes](https://github.com/krissen/pollenprognos-card/releases/tag/v1.0.6) of pollenprognos-card v1.0.6.

**Comment by Dav-rnd** [comment]
Hi @krissen,
I have downloaded v1.1.0b as suggested:
![Image](https://github.com/user-attachments/assets/a940ca3e-d44f-4423-8722-9491eb61e13c)

And added the custom text config as advised on the README. I just copy-pasted the exact yaml at the bottomn of the README page, so I won't copy-paste it again here.
I have also cleared the cache and created a brand new card, just in case.

Here is what is displayed in HA dashboard:
![Image](https://github.com/user-attachments/assets/a7a3c005-fd98-4689-8a99-4939390e4c47)

So the custom text is not shown in the card. Is there something I am doing wrong?

Also, it's a minor remark, but the screenshot at the bottom of the README shows all allergens, not only the ones with a level 1 minimum. This is confusing, and due to the line 'pollen_threshold: 1' in the config. So, for clarity I would advise to either update the screenshot, or change the pollen_threshold line.

**Comment by krissen** [comment]
> Also, it's a minor remark, but the screenshot at the bottom of the README shows all allergens, not only the ones with a level 1 minimum. This is confusing, and due to the line 'pollen_threshold: 1' in the config. So, for clarity I would advise to either update the screenshot, or change the pollen_threshold line.

Thank you! Updated.

Although you said you've verbatim copied the code from the example, could you nevertheless copy-paste it here as well? Not from the README obviously, but from your config. Pesky yaml with all those indents etc. Even though I personally might attempt to only copy-paste, sometimes tabs are introduced despite it shouldn't; sometimes a linter does something it shouldn't. Simply best to be sure. Thanks!

Regarding updating lovelace. Just to humour me, could you (from HA top-right menu) 1) reload; 2) update; 3) then force-refresh your view. I've found the above to sometimes be necessary for changes to take effect.

Lastly, this should not have any bearing on the issue at hand, but all v1.1.0b* will be pre-releases of support for custom phrases, so you can always download the last in that line. Currently, latest is [v1.1.0b2](https://github.com/krissen/pollenprognos-card/tree/v1.1.0b2).

From your screenshot, I can also see that I've removed too many umlauts (title, city). Will amend.

**Comment by krissen** [comment]
I updated the example in the branch README; only changes were prefixing title with a dash and indenting the whole block.

**Comment by krissen** [comment]
[v1.1.0b3](https://github.com/krissen/pollenprognos-card/releases/tag/v1.1.0b3) should give you umlauts for Malmö in the title of the card. :-)

Back to the issue. How the config code should look like, regarding indentation or dash/no dash depends on the context where you're pasting it into.

When I'm testing it in the UI editor, specifically editing the yaml of only one section, I can paste the config code in without dash or indentation:

![Image](https://github.com/user-attachments/assets/9124ce15-a7fe-4d3a-9712-4f36ab8afff0)

If, on the other hand, I'd be entering it in an entirely manual lovelace tab or some such, it would look different:

![Image](https://github.com/user-attachments/assets/22acb56b-76e6-4985-9b16-b260e2656a41)

Both of the above work.

**Comment by krissen** [comment]
To render this result, in a section using UI editor:

![Image](https://github.com/user-attachments/assets/42aa5a7f-0a1a-4841-9caf-f3908c28f135)

This exact code was used for config:

```
type: custom:pollenprognos-card
city: Malmö
show_text: true
minimal: false
sort: value_descending
pollen_threshold: 1
days_to_show: 2
date_locale: en-GB
allergens:
  - Al
  - Alm
  - Malörtsambrosia
  - Björk
  - Ek
  - Gråbo
  - Gräs
  - Hassel
  - Sälg och viden
phrases:
  full:
    Al: Alder
    Alm: Elm
    Malörtsambrosia: Ragweed
    Björk: Birch
    Ek: Oak
    Gråbo: Mugwort
    Gräs: Grass
    Hassel: Hazel
    Sälg och viden: Willow and sallow
  short:
    Al: Alder
    Alm: Elm
    Malörtsambrosia: Ragweed
    Björk: Birch
    Ek: Oak
    Gråbo: Mugwort
    Gräs: Grass
    Hassel: Hazel
    Sälg och viden: Willow
  levels:
    - No pollen
    - Low
    - Low-Moderate
    - Moderate
    - Moderate-High
    - High
    - Very high
  days:
    "0": Today
    "1": Tomorrow
    "2": Day after tomorrow
```
